config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'resources/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get    'sessions/new'
  get    'users/new'
  root   'pages#home'
  get    '/home',      to: 'pages#home'
  get    '/help',      to: 'pages#help'
  get    '/about',     to: 'pages#about'
  get    '/contact',   to: 'pages#contact'
  get    '/users/new', to: 'users#new'
  post   '/users/new', to: 'users#create'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  get    '/resources/new', to: 'resources#new'
  post    '/resources/new', to: 'resources#create'
  resources :users
  resources :user_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :resources
end

app/views/resources/_form.html.erb
<%= form_for @resource do |f| %>
  <%= render 'messages/resource_errors', object: @resource %>

  <%= f.label :title, "Resource title"  %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :description, "Description"  %>
  <%= f.text_field :description, class: 'form-control' %>

  <%= f.label :hourly_rate, "Hourly rate"  %>
  <%= f.number_field :hourly_rate, class: 'form-control', step: 0.01 %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/resources/_resource.html.erb
<tr>
  <td><%= resource.id %> </td>
  <td><%= resource.title %> </td>
  <td><%= resource.description %></td>
  <td>£ <%= resource.hourly_rate %></td>
  <td><%= link_to "View", resource_path(resource) %></td>
  <td><%= link_to "Edit", edit_resource_path(resource) %></td>
  <td><%= link_to "Delete", resource, method: :delete,
                  data: { confirm: "Confirm Account Deletion" } %>
  </td>
</tr>

app/views/resources/edit.html.erb
<% provide(:title, 'Resource Edit') %>
<% provide(:button_text, 'Save') %>
<h1>Resource Edit</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/resources/index.html.erb
<% provide(:title, 'Resources list') %>
<h1>Resources list</h1>

<div class="container">

  <div id="custom-search-input">
    <div class="input-group col-md-12">
      <input type="text" class="form-control input-lg" placeholder="Search" />
      <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
    </div>
  </div>
</div>
<br>


<div class="container">
  <div class="table-responsive">
    <table class="table table-striped table-index">
      <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Hourly rate</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>

      <%= render @resources %>

      </tbody>
    </table>
  </div>
</div>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/resources/new.html.erb
<% provide(:title, 'Resource Creation') %>
<% provide(:button_text, 'Create') %>
<h1>Resource Creation</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/resources/show.html.erb
<% provide(:title, "Resource Information") %>
<h1>Resource Information</h1>
<p>
  <%= @resource.title %>, <%= @resource.description %>, <%= link_to "Edit", edit_resource_path(@resource.id) %>
</p>