config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'resources/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get    'sessions/new'
  get    'users/new'
  root   'pages#home'
  get    '/home',      to: 'pages#home'
  get    '/help',      to: 'pages#help'
  get    '/about',     to: 'pages#about'
  get    '/contact',   to: 'pages#contact'
  get    '/users/new', to: 'users#new'
  post   '/users/new', to: 'users#create'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  get    '/resources/new', to: 'resources#new'
  post    '/resources/new', to: 'resources#create'
  resources :users
  resources :user_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :resources
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; 2018 MS Therapy Centre Lothian
  </small>
  <nav>
    <ul>
      <li><a href="https://github.com/kmclellan/mstc">Github repository</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to "MS Therapy Centre Lothian", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <nav>
      <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Info<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "About",    about_path %></li>
                  <li><%= link_to "Contact",  contact_path %></li>
                  <li><%= link_to "Help",     help_path %></li>
                </ul>
              </li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Your Profile<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Information", current_user %></li>
              <li><%= link_to "Edit Information", edit_user_path(current_user) %></li>
            </ul>
          </li>
          <% if admin? %>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">User management<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "User List", users_path %></li>
                <li><%= link_to "Create user", users_new_path %></li>
              </ul>
            </li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Resource management<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Resource list", resources_path %></li>
                <li><%= link_to "Create Resource", resources_new_path  %></li>
              </ul>
            </li>
          <% end %>
          <li><%= link_to "Log out", logout_path, method: :delete %> </li>
        <% else %>
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Contact",  contact_path %></li>
          <li><%= link_to "Help",     help_path %></li>
          <li><%= link_to "Signup",   users_new_path %></li>
          <li><%= link_to "Log in",   login_path %></li>
        <% end %>
      </ul>
      </div>
    </nav>
  </div>
</header>



app/views/layouts/_rails.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails' %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type} alert-dismissible") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>